apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # This has to select our client-deployment
    component: web
  ports:
    # Port 3000 of the service will map to 3000
    # of the pod (targetPort)
    - port: 3000
      targetPort: 3000