apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# We're not putting storageClassName here, to default
# to local. When deployed it will take the default for
# the provider unless you override it.